[platformio]
src_dir = .
default_envs = esp32c3-elrs-tx

[env]
framework = arduino
monitor_speed = 115200

[esp32_pioarduino]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board_build.partitions = no_ota.csv
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0

[env:esp32c3-elrs-tx]
extends = esp32_pioarduino
board = esp32-c3-devkitm-1
build_flags =
  -D MODULE_ESP32C3_ELRS_TX
  -D ARDUINO_ESP32C3_DEV
  -D ARDUINO_PARTITION_no_ota

[env:matek-mtx-db30]
extends = esp32_pioarduino
board = pico32
build_flags =
  -D MODULE_MATEK_MTX_DB30
  -D ARDUINO_ESP32_PICO
  -D ARDUINO_PARTITION_no_ota

[env:esp82xx-elrs-tx]
platform = espressif8266@4.2.1
board = esp8285
build_flags =
  -D MODULE_ESP82XX_ELRS_TX
  -D ARDUINO_ESP8266_ESP01
